from datetime import datetime

products = [
    {
        "id": 1,
        "name": "Clavier Mécanique RGB",
        "price": 2500,
        "quantity": 10,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 2,
        "name": "Souris Gamer Sans Fil",
        "price": 1500,
        "quantity": 20,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 3,
        "name": "Écran 27 pouces 4K",
        "price": 45000,
        "quantity": 5,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 4,
        "name": "Casque Audio Bluetooth",
        "price": 8900,
        "quantity": 15,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 5,
        "name": "Carte Graphique RTX 4060",
        "price": 125000,
        "quantity": 3,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 6,
        "name": "Processeur Intel i7",
        "price": 85000,
        "quantity": 7,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 7,
        "name": "RAM 16GB DDR5",
        "price": 12000,
        "quantity": 25,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 8,
        "name": "SSD 1TB NVMe",
        "price": 18000,
        "quantity": 12,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 9,
        "name": "Webcam HD 1080p",
        "price": 6500,
        "quantity": 8,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 10,
        "name": "Microphone Studio USB",
        "price": 9400,
        "quantity": 6,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 11,
        "name": "Enceinte Bluetooth Portable",
        "price": 7200,
        "quantity": 18,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 12,
        "name": "Chargeur Rapide 65W",
        "price": 3800,
        "quantity": 30,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 13,
        "name": "Câble HDMI 2.1 2m",
        "price": 1200,
        "quantity": 50,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 14,
        "name": "Station d'accueil USB-C",
        "price": 15600,
        "quantity": 4,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 15,
        "name": "Disque Dur Externe 2TB",
        "price": 21000,
        "quantity": 9,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 16,
        "name": "Clavier Compact Bluetooth",
        "price": 6800,
        "quantity": 14,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 17,
        "name": "Souris Érgonomique Verticale",
        "price": 4200,
        "quantity": 11,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 18,
        "name": "Tapis de Souris XXL",
        "price": 2800,
        "quantity": 22,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 19,
        "name": "Ventilateur PC 120mm",
        "price": 1800,
        "quantity": 16,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 20,
        "name": "Carte Mère ATX B760",
        "price": 42000,
        "quantity": 4,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    }
]

next_product_id = 21

users = [
    {
        "id": 1,
        "username": "john_doe",
        "email": "john.doe@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 2,
        "username": "jane_smith",
        "email": "jane.smith@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 3,
        "username": "mike_wilson",
        "email": "mike.wilson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 4,
        "username": "sarah_connor",
        "email": "sarah.connor@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 5,
        "username": "robert_brown",
        "email": "robert.brown@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 6,
        "username": "emily_davis",
        "email": "emily.davis@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 7,
        "username": "david_miller",
        "email": "david.miller@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 8,
        "username": "lisa_johnson",
        "email": "lisa.johnson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 9,
        "username": "chris_martin",
        "email": "chris.martin@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 10,
        "username": "amanda_lee",
        "email": "amanda.lee@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 11,
        "username": "james_wilson",
        "email": "james.wilson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 12,
        "username": "maria_garcia",
        "email": "maria.garcia@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 13,
        "username": "thomas_anderson",
        "email": "thomas.anderson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 14,
        "username": "jennifer_taylor",
        "email": "jennifer.taylor@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 15,
        "username": "daniel_moore",
        "email": "daniel.moore@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 16,
        "username": "patricia_white",
        "email": "patricia.white@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 17,
        "username": "kevin_brown",
        "email": "kevin.brown@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 18,
        "username": "laura_martinez",
        "email": "laura.martinez@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 19,
        "username": "steven_clark",
        "email": "steven.clark@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 20,
        "username": "michelle_rodriguez",
        "email": "michelle.rodriguez@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    }
]

next_user_id = 21