from datetime import datetime

users = [
    {
        "id": 1,
        "username": "john_doe",
        "email": "john.doe@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 2,
        "username": "jane_smith",
        "email": "jane.smith@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 3,
        "username": "mike_wilson",
        "email": "mike.wilson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 4,
        "username": "sarah_connor",
        "email": "sarah.connor@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 5,
        "username": "robert_brown",
        "email": "robert.brown@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 6,
        "username": "emily_davis",
        "email": "emily.davis@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 7,
        "username": "david_miller",
        "email": "david.miller@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 8,
        "username": "lisa_johnson",
        "email": "lisa.johnson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 9,
        "username": "chris_martin",
        "email": "chris.martin@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 10,
        "username": "amanda_lee",
        "email": "amanda.lee@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 11,
        "username": "james_wilson",
        "email": "james.wilson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 12,
        "username": "maria_garcia",
        "email": "maria.garcia@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 13,
        "username": "thomas_anderson",
        "email": "thomas.anderson@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 14,
        "username": "jennifer_taylor",
        "email": "jennifer.taylor@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 15,
        "username": "daniel_moore",
        "email": "daniel.moore@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 16,
        "username": "patricia_white",
        "email": "patricia.white@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 17,
        "username": "kevin_brown",
        "email": "kevin.brown@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "moderator",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 18,
        "username": "laura_martinez",
        "email": "laura.martinez@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": False,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 19,
        "username": "steven_clark",
        "email": "steven.clark@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "user",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    },
    {
        "id": 20,
        "username": "michelle_rodriguez",
        "email": "michelle.rodriguez@email.com",
        "password_hash": "HASH À FAIRE PLUS TARD",
        "role": "admin",
        "is_active": True,
        "created_at": datetime.now(),
        "updated_at": datetime.now(),
    }
]

next_user_id = 21